# Generated by Django 4.1 on 2022-08-06 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='', max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('annonymous', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField()),
                ('title', models.TextField(default='')),
                ('content', models.TextField(null=True)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
