# Generated by Django 4.1 on 2022-08-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_content_post_image_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='annonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
