# Generated by Django 4.1 on 2022-08-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_annonymous_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board',
            field=models.CharField(default='', max_length=100),
        ),
    ]
