# Generated by Django 4.0.6 on 2022-07-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='sexuality',
            new_name='gender',
        ),
    ]
