# Generated by Django 4.1 on 2022-08-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default="{% static 'img/account.png' %}", upload_to='images/'),
        ),
    ]
