# Generated by Django 4.1 on 2022-08-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='/static/img/account.png', upload_to='images/'),
        ),
    ]
