# Generated by Django 4.1 on 2022-08-06 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clothe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('image', models.ImageField(upload_to='images/')),
                ('season', models.TextField()),
                ('parent_category', models.TextField(default='')),
                ('child_category', models.TextField(default='')),
                ('favorite', models.BooleanField(default=False)),
                ('color', models.TextField()),
                ('style', models.TextField()),
                ('memo', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
