# Generated by Django 4.0.6 on 2022-08-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='image',
            field=models.BinaryField(),
        ),
    ]
