# Generated by Django 4.0.6 on 2022-08-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothe', '0002_alter_clothe_favorite_alter_clothe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
