# Generated by Django 4.0.6 on 2022-08-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothe', '0003_alter_clothe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
