# Generated by Django 4.1 on 2022-08-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothe', '0004_clothe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothe',
            name='category',
        ),
        migrations.AddField(
            model_name='clothe',
            name='child_category',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='clothe',
            name='parent_category',
            field=models.TextField(default=''),
        ),
    ]
