# Generated by Django 4.1 on 2022-08-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='annonymous',
            field=models.BooleanField(default=False),
        ),
    ]
